/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#define RCC_BASE 0x40021000
//#define GPIO_BASE (0x40010800)
//#define GPIO_CHR  *(volatile uint32_t*)(GPIO_BASE+0x04)
//#define GPIO_ODR  *(volatile uint32_t*)(GPIO_BASE+0x0c)
#define RCC_CR *(volatile uint32_t*)(RCC_BASE+0x00)
#define RCC_CFGR *(volatile uint32_t*)(RCC_BASE+0x04)
#define GPIO_BASE (0x40010800)
#define GPIO_CHR  *(volatile uint32_t*)(GPIO_BASE+0x04)
#define GPIO_ODR  *(volatile uint32_t*)(GPIO_BASE+0x0c)
#define RCC_APB2ENR *(volatile uint32_t*)(RCC_BASE+0x18)
int main(void)
{
	int i ;
	RCC_APB2ENR|=(1<<2);
	GPIO_CHR &=0xFF0FFFFF;
	GPIO_CHR |= 0x00200000;
	//RCC_CR |=(1<<0); // HSION ENB
	//	RCC_CFGR &= ~(1<<0);
	//RCC_CFGR &= ~(1<<16);// select the HSI / 2
	RCC_CFGR |= (0b0110<<18);// multiply 4MHz by 8 at pllmul
	RCC_CFGR |= (0b10<<0);// set the PLL as a system clocking
	RCC_CFGR |= (0b100<<8);// APB1 prescaler
	RCC_CFGR |= (0b101<<11);// APB2 prescaler
	RCC_CR |= (1<<24); // PLLON NOTE: you must open it after multiplication of pll
	while(1)
	{
		GPIO_ODR |= (1<<13);
		for (i = 0; i < 5000; ++i) ;
		GPIO_ODR &= ~(1<<13);
		for (i = 0; i < 5000; ++i) ;
	};
}

