/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103c6_gpio_driver.h"
#include "stm32f103x6.h"
#include "stm32f103c6_EXTI_driver.h"
#include "Lcd_drivier.h"
#include "keybad.h"
uint16_t flag ;
void my_wait(int x)
{
	int i , j ;
	for (i = 0; i < x; ++i) {
		for (j = 0; j < 255; ++j);
	}
}
void EXTI_CFG_Handler(void)
{
	flag=1;
	LCD_WRITE_STRING("this is EXTI_CFG_Handler ");
	my_wait(1000);
}
int main(void)
{
	// enable clock
	GPIOA_CLK_EN();
	GPIOB_CLK_EN();
	AFIO_CLK_EN();

	LCD_INIT();
	LCD_clear_screen();
	// configure EXTI
	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN=EXTI_EXTI9PB9;
	EXTI_CFG.IRQ_EN=EXTI_IRQ_Enable;
	EXTI_CFG.trigger_case=EXTI_Trigger_Rising;
	EXTI_CFG.P_IRQ_CallBack=EXTI_CFG_Handler;
	MCAL_EXTI_GPIO_Init(&EXTI_CFG);
	flag=1;
	while(1)
	{
		if(flag)
		{
			LCD_clear_screen();
			flag=0;
		}
	}
}
