/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103c6_gpio_driver.h"
#include "stm32f103x6.h"




void clock_init()
{
	// allow clocking for GPIO PORT B
	GPIOB_CLK_EN();
	// allow clocking for GPIO PORT A
	GPIOA_CLK_EN();
}
void GPIO_init()
{
	// for portA
	// pin1 input with external pull up
	GPIO_PinConfig_t pin;
	pin.PinNumber=GPIO_PIN_1;
	pin.PinMode=GPIO_MODE_Input_FLO;
	MCAL_GPIO_Init(GPIOA,&pin);
	// pin13 input with external pull down
	pin.PinNumber=GPIO_PIN_13;
	pin.PinMode=GPIO_MODE_Input_FLO;
	MCAL_GPIO_Init(GPIOA,&pin);

	// for portB
	// pin1 output push-pull
	pin.PinNumber=GPIO_PIN_1;
	pin.PinMode=GPIO_MODE_Output_PP;
	pin.OutPutSpeed=GPIO_SPEED_10M;

	MCAL_GPIO_Init(GPIOB,&pin);
	// pin13 output push-pull
	pin.PinNumber=GPIO_PIN_13;
	pin.PinMode=GPIO_MODE_Output_PP;
	pin.OutPutSpeed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB,&pin);
}
int main(void)
{
	clock_init();
	GPIO_init();
	while(1)
	{
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1)==0)//read gpio port a pin 1
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1)==0);
		}
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13)==1)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);


		}
		wait(1);
	}
}
