/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
//-------------------------clocks-----------------//
#define RCC_BASE 0x40021000
#define RCC_APB2RSTR *(volatile uint32_t*)(RCC_BASE+0x0c)
//------------------GPIO---------------------------//
#define GPIO_BASE (0x40010800)
#define GPIO_CRL     *(volatile uint32_t*)(GPIO_BASE+0x00)
#define GPIO_CHR     *(volatile uint32_t*)(GPIO_BASE+0x04)
#define GPIO_ODR     *(volatile uint32_t*)(GPIO_BASE+0x0c)
#define AFIO_EXTICR1 *(volatile uint32_t*)(AFIO_BASE+0x08)
#define  AFIO_BASE   0x40010000
//------------------------EXTI----------------------//
#define EXTI_BASE 0x40010400
#define EXTI_IMR *(volatile uint32_t*)(EXTI_BASE+0x00)
#define EXTI_RTSR *(volatile uint32_t*)(EXTI_BASE+0x08)
#define EXTI_PR *(volatile uint32_t*)(EXTI_BASE+0x14)
#define NVIC_ISER0 *(volatile uint32_t*)(0xE000E100)
void clock_init()
{
	RCC_APB2RSTR |= (1<<2); // enable clocks for GPIO Port A
	RCC_APB2RSTR |= (1<<0); // enable clocks for AFIO
}


void GPIO_init()
{
	// pin 13 output
	GPIO_CHR &= 0xff0fffff;
	GPIO_CHR |= 0x00200000;
	// pin 0 input
	GPIO_CRL |= (1<<2);
}
void EXTI0_init()
{
	// select Port A pin 0 as EXTI0
	AFIO_EXTICR1=0;
	// UN mask EXTI0 line
	EXTI_IMR|= (1<<0);
	// enable rising trigger
	EXTI_RTSR|= (1<<0);
	// enable mask at nvic
	NVIC_ISER0|=(1<<6);
}

int main(void)
{
	clock_init();
	GPIO_init();
	EXTI0_init();
	while(1);
}

void EXTI0_IRQHandler()
{
	GPIO_ODR^=(1<<13);
	EXTI_PR|=(1<<0);
}
