/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "stm32f103x6.h"
#include "stm32f103c6_gpio_driver.h"
#include "stm32f103c6_EXTI_driver.h"
#include "stm32f103c6_UART_driver.h"
#include "stm32f103c6_SPI_driver.h"
#include "stm32f103c6_I2C_driver.h"
#include "I2C_Slave_EEPROM.h"

int main(void)
{
	// enable clock
	GPIOA_CLK_EN();
	GPIOB_CLK_EN();
	AFIO_CLK_EN();
	uint8_t ch1[]={0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	uint8_t ch2[]={0};
	// test case 1
	eeprom_init();
	eeprom_write(0xAF, ch1, 7);
	eeprom_read(0xAF, ch2, 7);
	// test case 2
	ch1[0] = 0xA;
	ch1[1] = 0xB;
	ch1[2] = 0xC;
	ch1[3] = 0xD;
	eeprom_write(0xFFF, ch1, 4);
	eeprom_read(0xFFF, ch2, 4);
	while(1)
	{

	}
}
